# 서블릿 인코딩 강제 설정
server:
  port: 8083
  servlet:
    encoding:
      force: true

# Spring Devtools 설정과 H2 웹 콘솔 활성화 통합
spring:
  batch:
    job:
      names: testJob1 # 실행할 배치 잡의 이름 설정
      enabled: true # false = 배치 작업 비활성화되고 특정 조건을 충족하지 않는 경우 실행을 막고자 할 때 유용.
    jdbc:
      initialize-schema: embedded # 배치 메타데이터 스키마 초기화 설정 (embedded 또는 none)
    #  initialize-schema: always # 배치 메타데이터 스키마를 항상 초기화 하도록 한다. 테스트 할 때 유용함.
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  h2:
    console:
      enabled: true




  # Thymeleaf 설정
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:templates/ # 여기에 경로쓰면 기본 경로로 됨. ㅎㅅㅎ
    check-template-location: true
    suffix: .html
    mode: HTML

  # Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        org:
          hibernate:
            SQL: DEBUG
            type:
              descriptor:
                sql:
                  BasicBinder: TRACE
        show_sql: false
    defer-datasource-initialization: true

  # 데이터베이스 설정
  datasource:
    generate-unique-name: false

  # 데이터베이스 설정

    url: jdbc:mysql://localhost:3306/pos
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver




